name: 🐞 Bug report
description: Report a bug or issue
labels: Bug
body:
 - type: textarea
   attributes:
    label: Issue description
    description: Explain clearly what the issue is and how it happens.
    placeholder: Tell us here about the bug/problem
   validations:
    required: true
 - type: textarea
   attributes:
    label: How to reproduce this issue?
    description: Try to explain what you did for the bug to occur. A good explanation of steps to reproduce helps us locate the bug faster. If applicable, add screenshots to help explain your problem.
    placeholder: |
      Step 1: ...
      Step 2: ...
      ...
   validations:
     required: true
 - type: textarea
   attributes:
    label: Details
    description: To understand the issue, we need some details of your setup & system
    placeholder: |
      Mod version: [2.0.0]
      Generator version: [Forge-1.20.1]
   validations:
     required: true
 - type: textarea
   attributes:
    label: Logs
    description: |
      If applicable, include your crash report or game .log file from the client session and/or server session.
    placeholder: Drag and drop files directly to here.
   validations:
    required: false
